version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:2017
  mongo-seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./initUser.json:/unitUser.json
    command: 'mongoimport --host mongodb --db users -- collection users --type json --file /initUser.json --jsonArray'
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
  user:
    build:
      context: ./
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    restart: on-failure
    links:
      - 'rabbitmq'



